services:
  db:
    image: postgres:17.4@sha256:81f32a88ec561664634637dd446487efd5f9d90996304b96210078e90e5c8b21
    restart: always
    environment:
      POSTGRES_DB: "$POSTGRE_DATABASE_NAME"
      POSTGRES_USER: "$POSTGRE_USER"
      POSTGRES_PASSWORD: "$POSTGRE_PASSWORD"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # A random available public port will be assigned. To retrieve its value: `docker compose port db 5432`

volumes:
  db_data:
